var IMAGES = {};
IMAGES.background = new Image();
IMAGES.background.src = "assets/background.jpg";
IMAGES.wall = new Image();
IMAGES.wall.src = "assets/wall.gif";
IMAGES.brick = new Image();
IMAGES.brick.src = "assets/brick.gif";
IMAGES.wall2 = new Image();
IMAGES.wall2.src = "assets/wall2.gif";
IMAGES.mario = new Image();
IMAGES.mario.src = "assets/mario.png";
IMAGES.mario2 = new Image();
IMAGES.mario2.src = "assets/mario_color.png";
IMAGES.koopa = new Image();
IMAGES.koopa.src = "assets/shell.png";
IMAGES.peach = new Image();
IMAGES.peach.src = "assets/peach.png";
IMAGES.mushroom = new Image();
IMAGES.mushroom.src = "assets/mushroom.png";
IMAGES.star = new Image();
IMAGES.star.src = "assets/star.png";
IMAGES.balloon = new Image();
IMAGES.balloon.src = "assets/balloon.png";

var SONGS = {};
/*SONGS.world = new Audio();
SONGS.world.src = "sounds/world_music.mp3";
//SONGS.world.loop();
SONGS.world.loop = true;
SONGS.world.play();*/
SONGS.jump = new Audio();
SONGS.jump.src = "sounds/jump.wav";